# Generated by Django 4.0.4 on 2022-06-01 15:58

import connected.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, verbose_name='Profile Picture'),
        ),
    ]
