# Generated by Django 4.0.4 on 2022-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0004_remove_educator_profile_user_educator_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('course_duration', models.CharField(max_length=64)),
                ('course_type', models.CharField(max_length=64)),
            ],
        ),
    ]
