# Generated by Django 4.0.4 on 2022-06-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0005_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
