# Generated by Django 4.0.4 on 2022-06-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0006_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
