# Generated by Django 4.0.4 on 2022-06-03 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connected', '0007_user_profile_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='educator_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='educator_profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='educator_profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='educator_profile',
            name='users',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
