# Generated by Django 4.0.4 on 2022-06-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0008_remove_educator_profile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educator_profile',
            old_name='users',
            new_name='user',
        ),
    ]
