# Generated by Django 4.0.4 on 2022-06-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0011_remove_user_profile_id_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator_profile',
            name='cv',
            field=models.FileField(default='', upload_to='cvs/pdfs/'),
        ),
        migrations.AddField(
            model_name='educator_profile',
            name='educational_certificate',
            field=models.FileField(default='', upload_to='educational_certificates/pdfs/'),
        ),
        migrations.AddField(
            model_name='educator_profile',
            name='experince_certificate',
            field=models.FileField(default='', upload_to='experince_certificate/pdfs/'),
        ),
        migrations.AddField(
            model_name='educator_profile',
            name='optional_certificate',
            field=models.FileField(default='', upload_to='optional_certificate/pdfs/'),
        ),
    ]
