# Generated by Django 4.0.4 on 2022-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0012_educator_profile_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/covers/'),
        ),
    ]
