# Generated by Django 4.0.4 on 2022-06-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0013_alter_educator_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('course_duration', models.CharField(max_length=64)),
                ('course_schedule', models.FileField(default='', upload_to='course_schedule/pdfs/')),
                ('educator_name', models.CharField(max_length=64)),
                ('lesson_number', models.IntegerField(blank=True, default=0)),
                ('educators', models.ManyToManyField(blank=True, related_name='teachers', to='connected.educator_profile')),
                ('learners', models.ManyToManyField(blank=True, related_name='students', to='connected.user_profile')),
            ],
        ),
    ]
