# Generated by Django 4.0.4 on 2022-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0014_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
