# Generated by Django 4.0.4 on 2022-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0015_courses_course_type_alter_courses_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator_profile',
            name='gender_type',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('prefer_not_to_answer', 'prefer_not_to_answer')], default='prefer_not_to_answer', max_length=64),
        ),
    ]
