# Generated by Django 4.0.4 on 2022-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0017_remove_user_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator_profile',
            name='educational_degree',
        ),
        migrations.RemoveField(
            model_name='educator_profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='educator_profile',
            name='location',
        ),
        migrations.AddField(
            model_name='educator_profile',
            name='educational_degree_type',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Freelance', 'Freelance'), ('prefer_not_to_answer', 'prefer_not_to_answer')], default='Certificate', max_length=64),
        ),
        migrations.AddField(
            model_name='educator_profile',
            name='experience_level',
            field=models.CharField(choices=[('NO_Experince', 'NO_Experince'), ('1upto5years', '1upto5years'), ('6upto10years', '6upto10years'), ('More_than11years', 'More_than11years')], default='NO_Experince', max_length=24),
        ),
        migrations.AddField(
            model_name='educator_profile',
            name='location_type',
            field=models.CharField(choices=[('Khartoum', 'Khartoum'), ('Bahri', 'Bahri'), ('parent', 'Omdurman')], default='Khartoum', max_length=10),
        ),
        migrations.AlterField(
            model_name='educator_profile',
            name='teaching_level',
            field=models.CharField(choices=[('School_level', 'School_level'), ('Undergraduate_level', 'Undergraduate_level'), ('Postgraduate_level', 'Postgraduate_level'), ('Freelances_level', 'Freelances_level')], default='School_level', max_length=24),
        ),
    ]
