# Generated by Django 4.0.4 on 2022-06-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0018_remove_educator_profile_educational_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator_profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='educator_profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='profile_pic',
        ),
    ]
