# Generated by Django 4.0.4 on 2022-06-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0019_remove_educator_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TID', models.IntegerField()),
                ('conf_TID', models.IntegerField()),
                ('phone_num', models.CharField(max_length=15)),
                ('conf_ph', models.CharField(max_length=15)),
            ],
        ),
    ]
