# Generated by Django 4.0.4 on 2022-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0020_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_schedule',
            field=models.CharField(default='', max_length=64),
        ),
    ]
