# Generated by Django 4.0.4 on 2022-06-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0023_alter_user_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='educator_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
