# Generated by Django 4.0.4 on 2022-06-08 15:09

import connected.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0025_remove_courses_educator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='educator_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='educator_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=connected.models.path_and_rename, verbose_name='Profile Picture'),
        ),
    ]
