# Generated by Django 4.0.4 on 2022-06-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected', '0027_remove_courses_educator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator_profile',
            name='gender_type',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('prefer_not_to_answer', 'prefer_not_to_answer')], default='prefer_not_to_answer', max_length=64),
        ),
    ]
